# Generated by Django 4.2.8 on 2025-11-19 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='創建時間'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='最後更新時間'),
                ),
                (
                    'order_number',
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name='訂單編號'
                    ),
                ),
                (
                    'total_price',
                    models.PositiveIntegerField(default=0, verbose_name='訂單總價'),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='創建時間'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='最後更新時間'),
                ),
                (
                    'uuid',
                    models.UUIDField(
                        primary_key=True, serialize=False, verbose_name='商品 UUID'
                    ),
                ),
                (
                    'product_name',
                    models.CharField(max_length=100, verbose_name='商品名稱'),
                ),
                ('price', models.PositiveIntegerField(verbose_name='商品價格')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductSnapshot',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='創建時間'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='最後更新時間'),
                ),
                (
                    'product_name',
                    models.CharField(max_length=100, verbose_name='商品名稱'),
                ),
                ('price', models.PositiveIntegerField(verbose_name='商品價格')),
                ('quantity', models.PositiveIntegerField(verbose_name='商品數量')),
                (
                    'order',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='api.order',
                        verbose_name='訂單',
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='api.product',
                        verbose_name='商品',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
