# Generated by Django 4.2.8 on 2025-11-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='創建時間'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='最後更新時間'),
                ),
                (
                    'order_number',
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name='訂單編號'
                    ),
                ),
                ('total_price', models.PositiveIntegerField(verbose_name='訂單總價')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
